/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UmeCol {
        /**
          * If true, will be hidden on mobile resolutions (under 640px).
         */
        "hideMobile": boolean;
        /**
          * Size in grid units, 1 - 12.
         */
        "size": number;
    }
    interface UmeImage {
        /**
          * Alternative Text
         */
        "alt": string;
        /**
          * Should the image cover the full width of the image itself.
         */
        "cover": boolean;
        /**
          * Height of image in px or rem.
         */
        "height": number;
        /**
          * Opacity value; Integer 0 - 100.
         */
        "opacity": number;
        /**
          * Image source url.
         */
        "src": string;
        /**
          * Width of image in px or rem.
         */
        "width": number;
    }
    interface UmeLayout {
        /**
          * If `true` spans the full width of it's container.
         */
        "fluid": boolean;
    }
}
declare global {
    interface HTMLUmeColElement extends Components.UmeCol, HTMLStencilElement {
    }
    var HTMLUmeColElement: {
        prototype: HTMLUmeColElement;
        new (): HTMLUmeColElement;
    };
    interface HTMLUmeImageElement extends Components.UmeImage, HTMLStencilElement {
    }
    var HTMLUmeImageElement: {
        prototype: HTMLUmeImageElement;
        new (): HTMLUmeImageElement;
    };
    interface HTMLUmeLayoutElement extends Components.UmeLayout, HTMLStencilElement {
    }
    var HTMLUmeLayoutElement: {
        prototype: HTMLUmeLayoutElement;
        new (): HTMLUmeLayoutElement;
    };
    interface HTMLElementTagNameMap {
        "ume-col": HTMLUmeColElement;
        "ume-image": HTMLUmeImageElement;
        "ume-layout": HTMLUmeLayoutElement;
    }
}
declare namespace LocalJSX {
    interface UmeCol {
        /**
          * If true, will be hidden on mobile resolutions (under 640px).
         */
        "hideMobile"?: boolean;
        /**
          * Size in grid units, 1 - 12.
         */
        "size"?: number;
    }
    interface UmeImage {
        /**
          * Alternative Text
         */
        "alt": string;
        /**
          * Should the image cover the full width of the image itself.
         */
        "cover"?: boolean;
        /**
          * Height of image in px or rem.
         */
        "height"?: number;
        /**
          * Opacity value; Integer 0 - 100.
         */
        "opacity"?: number;
        /**
          * Image source url.
         */
        "src": string;
        /**
          * Width of image in px or rem.
         */
        "width"?: number;
    }
    interface UmeLayout {
        /**
          * If `true` spans the full width of it's container.
         */
        "fluid"?: boolean;
    }
    interface IntrinsicElements {
        "ume-col": UmeCol;
        "ume-image": UmeImage;
        "ume-layout": UmeLayout;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ume-col": LocalJSX.UmeCol & JSXBase.HTMLAttributes<HTMLUmeColElement>;
            "ume-image": LocalJSX.UmeImage & JSXBase.HTMLAttributes<HTMLUmeImageElement>;
            "ume-layout": LocalJSX.UmeLayout & JSXBase.HTMLAttributes<HTMLUmeLayoutElement>;
        }
    }
}
